name-template: 'jQuery Manager v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'Feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Fix'
      - 'Bug'
  - title: '🔒 Security Updates'
    labels:
      - 'Security'
  - title: '🧰 Maintenance'
    labels:
      - 'Library'
      - 'Code Climate'
      - 'Docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  # What's changed (changelog)
  $CHANGES
  ## Thanks to
  $CONTRIBUTORS
