name-template: 'jQuery Manager v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'Feature'
  - title: '🐛 Bug fixes'
    labels:
      - 'Fix'
      - 'Bug'
  - title: '🔒 Security updates'
    labels:
      - 'Security'
  - title: '🧰 Maintenance'
    labels:
      - 'Library'
      - 'Code Climate'
      - 'Docs'
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  # What's changed (changelog)
  $CHANGES
  
  ## 👍 Thanks to
  $CONTRIBUTORS
  
  ## [Download latest version](https://downloads.wordpress.org/plugin/jquery-manager.zip) from [wordpress.org](https://wordpress.org/plugins/jquery-manager/)
